name: meu_app
description: Um novo app Flutter
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  # outras dependências aqui...

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1  # ou a versão mais recente

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  fonts:
    - family: AlumnSansSC #fonts baixadas manual e imagens
      fonts:
       - asset: assets\fonts\AlumniSansSC-Italic-VariableFont_wght.ttf
       - asset: assets\fonts\AlumniSansSC-VariableFont_wght.ttf
  assets:
    - assets/icon/
    - assets/imagens/data.json
